version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - SA_PASSWORD=Tiptoen13509
      - ACCEPT_EULA=Y
    ports:
      - "1660:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: